app/library/urls.py
from django.urls import re_path, path

from . import views

app_name = 'library'

urlpatterns = [
    re_path('gain_access/(?P<ct_id>\d+)/', views.GainAccess.as_view(), name='gain_access'),
    path('list/', views.CategoryList.as_view(), name='categories_list'),
    path('add/', views.CategoryAdd.as_view(), name='add_category'),
    re_path('remove/(?P<ct_id>\d+)/', views.CategoryRemove.as_view(), name='remove'),
]

app/social/urls.py
from django.urls import path, re_path
from . import views


app_name = 'social'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('signin/', views.SignIn.as_view(), name='signin'),
    path('signout/', views.SignOut.as_view(), name='signout'),

    path('my/', views.My.as_view(), name='my'),
    re_path('(?P<user_id>\d+)/', views.UserView.as_view(), name='user'),
    path('settings/', views.MySettings.as_view(), name='settings'),
    path('list/', views.UserList.as_view(), name='users_list'),
]

app/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('app.index.urls', namespace='index')),
    url(r'^', include('app.library.urls', namespace='library')),
    url(r'^users/', include('app.social.urls', namespace='social')),
]

templates/base.html
<!DOCTYPE html>
{% load bootstrap3 %}
<html{% if LANGUAGE_CODE %} lang="{{ LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block bootstrap3_title %}Научный репозиторий ИУ5{% endblock %}</title>
    {% bootstrap_css %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
    {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fontawesome/web-fonts-with-css/css/fontawesome-all.css' %}">
        <link rel="stylesheet" href="{% static 'media/image' %}">
</head>

    <body>
        <div id="header" class="navbar navbar-expand-lg fixed-top navbar-light bg-light row">
            <div class="col-2"></div>
            <div class="col-2">
                    <nav class="navbar navbar-light ">
                        <a class="navbar-brand" href=" http://127.0.0.1:8000">
                            <img src="{% static 'media/image/Gerb_MGTU_imeni_Baumana.png' %}" width="45" height="45" class="d-inline-block align-content-center" alt="">
                            Научный репозиторий</a>
                    </nav>
            </div>
            <div class="col-1">
                <a href="{% url 'social:users_list' %}" class="users">Пользователи</a>
            </div>
            <div class="col-2">
                {% if request.user.can_create %}
                <a href="{% url 'library:add_category' %}" class="users">Добавить раздел</a>
                {% endif %}
            </div>
            <div class="col-1"></div>
            <div class="col-3">
                {% if not request.user.is_authenticated %}
                   <div class="user_block">
                        <div class="user_name"></div>
                        <div class="user_menu">
                            <a href="{% url 'social:signin' %}" class="login">Вход</a> |
                            <a href="{% url 'social:signup' %}" class="register">Регистрация</a>
                        </div>
                    </div>
                {% else %}
                    <img id="nav-avatar" style="margin-right: 10px" height="40" width="40" class="float-left" src={% static 'media/image/no_avatar.png'%}>
                    <a href="{% url 'social:my' %}" class="user-name">{{ request.user.first_name }} {{ request.user.last_name }}</a>
                    <div class="user_menu">
                        <a href="{% url 'social:settings' %}" class="settings">Настройки</a>&nbsp;&nbsp;&nbsp;
                        <a href="{% url 'social:signout' %}" class="logout">Выход</a>
                    </div>
                {% endif %}
            </div>
        </div>
       {% block content %}
       {% endblock %}
        <nav id="down" class="navbar navbar-default navbar-fixed-bottom navbar-inverse row" st>
            <p class="navbar-text">МГТУ им. Н.Э. Баумана </p> <p class="navbar-text"><span class="glyphicon glyphicon-earphone"> 8(499)-267-54-34</span></p>
            <p class="navbar-text">2-я Бауманская ул., д. 5, 9 этаж (Главный Учебный Корпус)</p>
        </nav>
    </body>
</html>

templates/category_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
 <div class="container">
    <div class="row">
        <div class="col-md-10 ">
            <form action="{% url 'library:categories_list' %}" method="get">
            <div id="search" class="input-group input-group-lg">
                <input id="text-search" type="text" class="form-control" name="q" placeholder="Введите запрос">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">Найти</button>
                </span>
            </div>
            </form>
        </div>
    </div>
    </div>
    <div class="container">
    <div id="ex" class="row">
        <div class="col-md-6">
            <h2><b>Список разделов</b></h2>
            {% if not object_list %}
                <br>
                По вашим критериям нет ни одного раздела
            {% endif %}
            {% for ct in object_list %}
                {% if ct in granted or ct.access == 1 %}
                    <p> <a href="#">{{ ct }}</a></p>
                {% elif ct in request.user.categories.all %}
                {{ ct }}
                    <i>(Запрос на доступ ожидает модерацию)</i>
                {% else %}
                    <a href="{% url 'library:gain_access' ct.id %}">
                        {{ ct }}
                        <button id="btn_acces" type="submit" class="btn btn-primary">Запросить доступ</button>
                    </a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1 id="reg"  class="form-signin-heading">{{ title }}</h1>
            <br />
            <form class="form-horizontal" action="{{ action }}" method="post">
                {{ form.non_field_errors }}
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    <label class="control-label col-xs-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div class="col-xs-9">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}
                <br/>
                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input id="btn-reg" type="submit" class="btn btn-primary btn-lg" value="{{ title }}">
                        {% if reset %}
                        <input id="btn-clean" type="reset" class="btn btn-default btn-lg" value="Очистить форму">
                        {% endif %}
                    </div>
                </div>
            </form>
            {% if request.GET.success %}
            <h2>Успешно!</h2>
            {% endif %}
        </div>
    </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load library_extra %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-12">
            <div id="text-rep" class="page-header">
                <h1>Научный репозиторий кафедры <a href="http://iu5.bmstu.ru/"> ИУ5 "Системы обработки информации и управления"</a></h1>
            </div>
        </div>
    </div>
    </div>
    <div class="container">
    <div class="row">
        <div class="col-md-10 ">
            <form action="{% url 'library:categories_list' %}" method="get">
                <div id="search" class="input-group input-group-lg">
                    <input id="text-search" type="text" class="form-control" placeholder="Введите запрос" name="q">
                    <span class="input-group-btn">
                        <button type="submit" class="btn btn-primary">Найти</button>
                    </span>
                </div>
            </form>
        </div>
    </div>
    </div>
    <div class="container">
    <div id="ex" class="row">
        <div class="col-md-10">
            <p>Например: <a href="{% url 'library:categories_list' %}?q=Средства АСОИУ">средства АСОИУ</a></p>
        </div>
    </div>
    </div>
    <div class="container">
    <div id="sec" class="row">
        <div class="col-md-6">
            <h1>Доступные разделы</h1>
            <div id="pop" class="row">
                <div class="col-md-12 brd">
                    {% for ct in public %}
                    <p>{{ ct }}{% if ct in can_delete %} <a href="{% url 'library:remove' ct.id %}">del</a>{% endif %}</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% if private %}
        <div class="col-md-6">
            <h1>Закрытые разделы</h1>
            <div id="pop" class="row">
                <div class="col-md-12 brd">
                    {% for ct in private %}
                    <p>
                        {% if ct in granted or ct in request.user.categories %}
                        <p>{{ ct }}</p>
                        {% elif ct in request.user.accessed_categories.all %}
                        {{ ct }}
                        <i>(Запрос на доступ ожидает модерацию)</i>
                        {% else %}
                        <a href="{% url 'library:gain_access' ct.id %}">
                        {{ ct }}
                            <button id="btn_acces"  class="btn btn-primary">Запросить доступ</button>
                        </a>
                        {% endif %}
                    </p>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    </div>
    </div>
{% endblock %}

templates/settings.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
             <h1 id="reg"  class="form-signin-heading">{% if editable %}Настройки{% else %}Информация{% endif %}</h1>
            <form class="form-horizontal" action="{% url 'social:settings' %}" method="post">
                {{ form.non_field_errors }}
                {% csrf_token %}
                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% else %}
                        <div class="form-group">
                            {{ field.errors }}
                            <label class="control-label col-xs-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                            <div class="col-xs-9">
                                {{ field }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
              <br />
            {% if editable %}
              <div class="form-group">
                  <div class="col-md-offset-3 col-md-9">
                      <input id="btn-reg" type="submit" class="btn btn-primary btn-lg" value="Сохранить">
                      <input id="btn-clean" type="reset" class="btn btn-default btn-lg" value="Очистить форму">
                  </div>
              </div>
            {% elif user == request.user %}
              <div class="form-group">
                  <div class="col-md-offset-3 col-md-9">
                      <a href="{% url 'social:settings' %}"><input id="btn-reg" class="btn btn-primary btn-lg" value="Редактировать"></a>
                  </div>
              </div>
            {% endif %}
            </form>
        </div>
    </div>
        <br>
    {% if user.categories.exists %}
    <div class="row">
    <div class="col-md-8 col-md-offset-3">
        <h2><b>Список разделов пользователя</b></h2>
        <br>
        {% for ct in user.categories.all %}
            <p>{{ ct }}</p>
        {% endfor %}
    </div>
    </div>
    {% endif %}

    </div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form class="form-horizontal" role="form" action="{% url 'social:signin' %}" method="post">
                <h1 id="enter" class="form-signin-heading">Вход</h1>
                <br />
                {{ form.non_field_errors }}
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group">
                    {{ field.errors }}
                    <label class="control-label col-xs-3" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    <div class="col-xs-9">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input id="btn-enter" type="submit" class="btn btn-lg btn-primary btn-block" value="Войти">
                    </div>
                </div>
            </form>
        </div>
    </div>
    </div>
{% endblock %}

templates/user_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
 <div class="container">
    <div class="row">
        <div class="col-md-10 ">
            <form action="{% url 'social:users_list' %}" method="get">
            <div id="search" class="input-group input-group-lg">
                <input id="text-search" type="text" class="form-control" name="q" placeholder="Введите запрос">
                <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary">Найти</button>
                </span>
            </div>
            </form>
        </div>
    </div>
    </div>
    <div class="container">
    <div id="ex" class="row">
        <div class="col-3">
           <h2>Группы пользователей</h2>
           <p><a href="{% url 'social:users_list' %}"{% if not request.GET.group_id %} style="text-decoration: underline">{% endif %}>Все пользователи</a></p>
           {% for group in groups %}
           <p><a href="{% url 'social:users_list' %}?group_id={{ group.id }}"{% if request.GET.group_id == group.id|slugify %} style="text-decoration: underline">{% endif %}>{{ group }}</a></p>
           {% endfor %}
        </div>
        <div class="col-3">
        <h2><b>Список пользователей</b></h2>
        {% if not object_list %}
            <br>
            По вашим критериям нет ни одного пользователя
        {% endif %}
        {% for user in object_list %}
        <p><a href="{% url 'social:user' user.id %}">{{ user }}</a></p>
        {% endfor %}
        </div>
        {% if request.GET.group_id %}
        <div class="col-4">
            <h2>Права группы пользователей</h2>
            <ul>
            {% if group.name == 'Администраторы' %}
                <li>Все права</li>
            {% elif group.name == 'Редакторы' %}
                <li>Выдача прав на каталоги</li>
                <li>Создание каталогов</li>
            {% elif group.name == 'Научные работники' %}
                <li>Редактирование своих каталогов</li>
                <li>Создание каталогов</li>
            {% elif group.name == 'Читатели' %}
                <li>Только чтение</li>
            {% endif %}
            </ul>
        </div>
        {% endif %}
    </div>
    </div>
{% endblock %}